services:
  server:
    build:
      context: .
      target: development
    ports:
      - "8080:443"
    environment:
      - SERVER_PORT=443
      - MYSQL_URL=jdbc:mysql://db/getTasksDone
    volumes:
      - ./:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=getTasksDone
      - MYSQL_PASSWORD=getTasksDone
      - MYSQL_DATABASE=getTasksDone
    volumes:
      - db_data:/var/lib/mysql
      - db_config:/etc/mysql/conf.d
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
volumes:
  db_data:
  db_config:
