version: '3.8'
services:
  server:

  #**********************************************************************
  # 
  # 
  #*********************************************************************

    restart: always
    image: ghcr.io/hackingsecurity/feature:4eb7faa653321b07992ba4bcf1fbd37506bc4ef1
    container_name: spring_boot_server
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://db/getTasksDone
    volumes:
      - ./:/tmp/app
    depends_on:
      db:
        condition: service_healthy


  #**********************************************************************
  # Creación de la base de datos
  # -> ver como no exponer contraseñas y usuarios
  #*********************************************************************
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=getTasksDone
      - MYSQL_PASSWORD=getTasksDone
      - MYSQL_DATABASE=getTasksDone
    volumes:
      - db_data:/var/lib/mysql
      - db_config:/etc/mysql/conf.d
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  db_data:
  db_config: